spring:
  application:
    name: group-booking
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/groupbooking}
    username: ${DB_USERNAME:your_username}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  sql:
    init:
      mode: never

server:
  port: 8080

logging:
  level:
    com.example.groupbooking: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE